
GET localhost:8081/actuator/
Content-Type: application/json
###


GET localhost:8081/actuator/info
Content-Type: application/json
###


GET localhost:8081/actuator/health
Content-Type: application/json
###


GET localhost:8081/actuator/customerStaff/13355667790
Content-Type: application/json
###



POST localhost:8081/actuator/customerStaffCount/13355667791
Content-Type: application/json
###